persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Pour autoriser les connexions externes (ESP8266)
listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
